import { assertEquals } from "@std/assert";
import { resonantCollinearity } from "./main.ts";

const example = `\
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
`.trimEnd();

Deno.test(function addTest() {
  assertEquals(resonantCollinearity(example.split("\n")), 14);
});
